version: '3'

services:
        #nginx:
        #image: nginx:latest
        #volumes:
        #    - ./code-server.conf:/etc/nginx/sites-enabled/code-server.conf:ro
        #ports:
        #    - "80:80"   
    code-server:
        build: ./
            #image: codercom/code-server:latest
        user: "${UID}:${GID}"
        volumes:
                #- ${HOME}/.config:/home/coder/.config:rw
            - ${PWD}/:/home/coder/project:rw
        environment:
            - DOCKER_USER=${USER}
        ports:
            - "8080" 

#sudo docker rm -f $(sudo docker ps -aq) && sudo docker run -it --name code-server -p 127.0.0.1:8080:8080   -v "$HOME/.config:/home/coder/.config"   -v "$PWD:/home/coder/project"   -u "$(id -u):$(id -g)"   -e "DOCKER_USER=$USER"   codercom/code-server:latest
